### PR TITLE
Fixing undefined constant

### PR DESCRIPTION
**Pull request by IzzySoft**
typing into the TO field in composer caused SQL error due to undefined constant

### CODE REVIEW

**Comment by t3chguy** [comment]
Something looks wrong with the alignment on that but at least its functional. Its probably due to some weird settings in my regular Programming Environment (Sublime Text 3)
Its functional, so will accept and will just re-align it when I get the chance to;

Thanks!

**Comment by t3chguy** [comment]
It looks like for some stupid reason I had both spaces and a tab in that line. How weird

**Comment by IzzySoft** [comment]
> It looks like for some stupid reason I had both spaces and a tab in that line. How weird

Just wanted to tell you that: a mess of mixes. Do you want me to clean that up, replacing all tabs by 4 spaces? That would cure it. I'd take care for that in the other files as well then.

**Comment by t3chguy** [comment]
Nah its alright, just need to run Sublime Text's convert to Tabs/Spaces on it and it'll handle the project in one click, no idea how it happened in the first place;

thanks anyway though

**Comment by IzzySoft** [comment]
I'm already done with it (simple `sed` does it).

**Comment by t3chguy** [comment]
Hahah yeah, my main workstation is Windows, I use Linux on all my Servers though so could have used that there

**Comment by IzzySoft** [comment]
I use Linux only. My simple text editor takes care for that (yes, I'm old-school :stuck_out_tongue_winking_eye:)

**Pull request merged**
